<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Day 11</title>
</head>
<body>
<h1 style="background-color: greenyellow;">Activity 1: Basic Error Handling with Try-Catch</h1>
<h2>Task 1: Write a function that intentionally throws an error and use a try-catch block to handle the error and log an appropriate message to the console.</h2>
<h2>Task 2: Create a function that divides two numbers and throws an error if the denominator is zero. Use a try-catch block to handle this error.</h2>

<h1 style="background-color: greenyellow;">Activity 2: Finally Block</h1>
<h2>Task 3: Write a script that includes a try-catch block and a finally block. Log messages in the try, catch, and finally blocks to observe the execution flow.</h2>

<h1 style="background-color: greenyellow;">Activity 3: Custom Error Objects</h1>
<h2>Task 4: Create a custom error class that extends the built-in Error class. Throw an instance of this custom error in a function and handle it using a try-catch block</h2>
<h2>Task 5: Write a function that validates user input (e.g., checking if a string is not empty) and throws a custom error if the validation fails. Handle the custom error using a try-catch block.</h2>
  
<h1 style="background-color: greenyellow;">Activity 4: Error Handling in Promises</h1>
<h2>Task 5: Write a function that validates user input (e.g., checking if a string is not empty) and throws a custom error if the validation fails. Handle the custom error using a try-catch block.</h2>
<h2>Task 6: Create a promise that randomly resolves or rejects. Use .catch() to handle the rejection and log an appropriate message to the console.</h2>
<h2>Task 7: Use try-catch within an async function to handle errors from a promise that randomly resolves or rejects, and log the error message.</h2>

<h1 style="background-color: greenyellow;">Activity 5: Graceful Error Handling in fetch</h1>
<h2>Task 8: Use the fetch API to request data from an invalid URL and handle the error using .catch(). Log an appropriate error message to the console</h2>
<h2>Task 9: Use the fetch API to request data from an invalid URL within an async function and handle the error using try-catch. Log an appropriate error message.</h2>

<script src="ErrorHandling.js"></script>
</body>
</html>
